import { comfortaa, norms } from '@/system/fonts';
import './global.css';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'PROSTO MARKETPLACE',
  description: 'Generated by create next app',
  icons: {
    icon: './logo.png',
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru">
      <body className={`${comfortaa.variable} ${norms.variable}`}>{children}</body>
    </html>
  );
}
